### ISSUE TITLE
那目前是有分块上传还是没有?

### ISSUE THREAD

**Issue by maxmas** [qpwoeiru96/QUpload#1]
请问一下, 那目前是有分块上传还是没有?

**Comment by qpwoeiru96** [comment]
有的 不支持并发而已 需要前一个上传完毕 下一个才能开始

**Comment by maxmas** [comment]
那你说明就要改一下啰, 因为说明写着除了图片压缩预览以及分片上传没有之外其他差不多

**Comment by maxmas** [comment]
另外请问一下, 如果只允许使用HTML5的方式上传, 应如何配置?
就不需要再设定swf的路径了吧

**Comment by qpwoeiru96** [comment]
没有办法配置，因为这是自动判断的 如果能用HTML5 绝对只用 HTML5 FLASH是IE9以下（含）的版本才开启的 不过这里有一个问题是 没有判断用户是否具有 Flash 的 runtime 
不过你不配置swf的path 那么也相当于只是能用html5的

**Comment by qpwoeiru96** [comment]
好的 我改一下说明

**Comment by maxmas** [comment]
谢谢你的回答, 再请问, 如果要用分片上传, 应如何配置, 范例里面好像是一般上传.
若配置分片上传后, 主机端PHP是否会自动合并档案呢?

**Comment by qpwoeiru96** [comment]
是分块上传，一次上传 BlockSize 完成之后传输下一个，所以主机不合并，只是Append。这样省去服务端合并、服务端碎片管理、客户端切割等等诸多问题。
