### ISSUE TITLE
android 版微信浏览器无法上传图片

### ISSUE THREAD

**Issue by zjkyz8** [qpwoeiru96/QUpload#2]
上传图片后七牛报错。
返回的错误是： {"error":"block 0: expect 567214 bytes but only 0 bytes uploaded"}
看request payload是有内容的

**Comment by qpwoeiru96** [comment]
请回复你七牛的详细的代码。
 payload 有内容说明文件是上传的。
请注意是分块上传的，所有块上传完之后，根据token取得文件才能进行七牛的上传操作。

**Comment by qpwoeiru96** [comment]
我居然操心七牛的错误，我也是傻傻的。。。。。。。
